### ISSUE TITLE
Crashes in Evaluations and Allocations

### ISSUE THREAD

**Issue by adrianlop** [jippi/hashi-ui#158]
Hi,

We're experiencing some issues with evaluations and allocations. The client has to render a lot of info and sometimes it crashes (either the Chrome tab, or a red error saying Websocket connection close please reload).

Maybe these pages need pagination or some other mechanism to avoid overload?
Thanks in advance! Great UI.

**Comment by jippi** [comment]
@adrianlop how many rows do you have in these lists? And what version of the UI do you use? :)

**Comment by adrianlop** [comment]
I'm using your latest docker image.
allocations: 1200+ rows
evaluations: 12200+ rows

I thought Nomad would purge old data but it is showing rows from 5months ago heheh. I tried PUT to Nomad's API in /v1/system/gc, but it won't purge old data.

Also, I've noticed that if I load the UI in /jobs or details of a job, after 2mins of inactivity, this message will appear:
![image](https://cloud.githubusercontent.com/assets/2879742/21179926/a78a30b6-c1f6-11e6-865a-df208b0c738d.png)

**Comment by jippi** [comment]
as for the timeout issue, do you proxy it through nginx or otherwise? I usually leave my prod hash-ui running for hours and hours idle on /jobs (without any websocket activity) and it doesn't disconnect. 

if you got old data like that, its a bug they fixed some time ago, to get rid of those old entries, you need to fully reset your cluster state. :( 

Thats a lot of rows, i've only tested with 2-500 rows on each view (allocations and evaluations) 

Having those lists more optimized (paginated on client or server) is on my todo, but its incredible hard since the concept of "page 1 or 2" is very moving target when new data comes in all the time, and we usually want newest data on top. I can imagine cases where you want to click "view" on an allocation on page 1, and then it suddenly goes away down to page 2 just 2ms before you click it, so you hit something else :(

**Comment by adrianlop** [comment]
@jippi thanks for the fast response.
yep that's my problem then :smile: I'll investigate further because we have the UI behind a HAProxy.

regarding the old data, I have Nomad 0.4.1, so fair enough, we will upgrade to 0.5.1 as soon as possible and purge the cluster state.
thanks a lot for the help!

**Comment by jippi** [comment]
@adrianlop I'll try to figure out how to make those lists faster, its currently unacceptable slow even on my ~200-300 items lists, so I'll keep it open as tracking issue for it

**Comment by adrianlop** [comment]
oh ok, that's great. thanks again!

**Comment by jippi** [comment]
@adrianlop Can you please give https://github.com/jippi/hashi-ui/pull/159 a try ?

**Comment by adrianlop** [comment]
@jippi sure I just tried it!
- Allocations tab is really fast now.
- Evaluations tab is faster but still freezes a bit (but remember I have 12k rows)
thanks a lot :D

**Comment by jippi** [comment]
I did not touch Evaluations yet :P since you say this fixed it, I'm going to close this issue and continue to fix it in #159

**Comment by adrianlop** [comment]
haha cool thanks! placebo effect on Evaluations :wink:
