### ISSUE TITLE
separate into different packages

### ISSUE THREAD

**Issue by waterdudu** [jippi/hashi-ui#185]
Currently all files are in main package, which is not likely the recommended way to layout go code.
It is better to separate files into different package, like package `consul`, `nomad` or `connection`. Thanks!

**Comment by jippi** [comment]
@waterdudu is this a refactor you want to take on? while it may not be the recommended way to lay out the code, it does work, and currently I prioritize my own time for features rather than big refactors. Also I'm currently not experienced enough in Go to do this task efficiently :)

**Comment by lfarnell** [comment]
I'm currently trying to re-do the CLI tooling and I'm experiencing the pain of no packages. Would either of you @waterdudu or @jippi able/willing to get this done? If someone even helps guide me I can try and attempt this, just don't know where to start.

**Comment by jippi** [comment]
I haven't had the pain or problem with a flat package, so not something I feel super urgently about doing - what problem are you hitting @lfarnell ?

**Comment by lfarnell** [comment]
The main problem @jippi that I'm currently facing is that most CLI libraries need to put the commands into a separate package. That's fine. So since that needs to happen, I would then need to move other code into distinct packages so that we can separate their concerns. The biggest problem is that when you create a package(say nomad or consul), you then can't refer to code in the main package from either of those packages. It then becomes increasingly difficult to work around that. I attempted to the first chunk of the re-org on a [branch](https://github.com/lfarnell/hashi-ui/tree/f-packages), so please check it out and let me know if you think I'm on the right track. I can also make it a PR and we could continue the discussion there.

**Comment by jippi** [comment]
Done
