### ISSUE TITLE
Add keepalive websocket messages

### ISSUE THREAD

**Issue by mclate** [jippi/hashi-ui#192]
In configurations, where backend is behind proxy, it is common to have proxy drop connection due to idle tcp session.

Would be nice to have client to send some dummy keepalive message in order to keep connection open (say, once every 45 seconds)

**Comment by jippi** [comment]
@mclate PR is welcome - otherwise, nginx and friends usually can be configured to include very high idle timeouts? :)

**Comment by mclate** [comment]
I'd love to, but unfortunately i have no knowledge of Go or js.

Idle timeouts is not the best thing to do really.
While idle timeout will solve the issue here, it will create extra burden on balancers and infrastructure. I'm pretty sure almost everyone here uses hashi-ui to support their primary application, thus timeout requirements are dictated by application needs in first place.
While one can configure nginx to have different timeouts for separate host, it is often hard or even impossible impossible to do so in other places. For example, AWS ELB can have only one timeout per ELB. (It doesn't really make sense to have separate ELB only for hashi-ui)
Another proxies might not allow you to update any timeouts at all.

IMO even a simple empty frame sent by client once in a while will solve the issue and prevent users from overcomplicating their infrastructure.

**Comment by Frick** [comment]
The WebSocket spec actually contains Ping and Pong frames (sometimes known as heartbeats) and an example in Go can be seen from the [Gorilla WebSocket](http://www.gorillatoolkit.org/pkg/websocket) library [here](https://github.com/gorilla/websocket/blob/master/conn.go#L1009-L1051). The browser should handle responding to Ping frames automatically I believe. This functionality isn't just good to keep otherwise idle connections open on load balancers, but also for the server to know when a client has died.

**Comment by jippi** [comment]
A fix should be in master now, the docker image should be updated in a few minutes :)

**Comment by mclate** [comment]
@jippi It works perfectly. Can confirm that there are no timeouts with new docker image. Thank you very much.

**Comment by jippi** [comment]
I tagged a new release too if you want to pin to that :)
