### ISSUE TITLE
Terraform UI

### ISSUE THREAD

**Issue by mytototo** [jippi/hashi-ui#222]
Is there any chance to see a UI for Terraform in this project? Or this is not the goal?

**Comment by lfarnell** [comment]
All hashicorp projects have the intention to be add but it's mostly just developer bandwidth at this time. PR's are always welcome for new features! :smile:

**Comment by jippi** [comment]
What @lfarnell said :)

**Comment by jrasell** [comment]
@jippi do you have any thoughts on how this work at a high level? I am happy to try and take a look into kicking this off.

**Comment by jippi** [comment]
I don't know much about terraform to be honest, never used it for anything serious - so not sure how a UI would fit on top of it to be honest :)

**Comment by lfarnell** [comment]
@jrasell What did you have in mind in terms of a UI? mirror terraform enterprise UI? I think this would be someone difficult currently due to the fact that Terraform does not have a Rest API like Nomad and Consul to even interact with. While you could execute commands via an exec, I think there is a better way, I just don't what that might look like right now. It would be interesting to know how the HashiCorp guys and gals do it. I'm currently facing the same problem with how to integrate Packer into hashi-ui.

**Comment by jrasell** [comment]
@lfarnell completely agree with you. 

One of the nice and possibly simpler draws of TFE is that you have a central library UI of all your TF modules which can then lead to features which allow interaction with those modules and such. The problem here is that modules and in general TF code can be stored in any number of Git/SVN stores which all use widely different APIs.

**Comment by parnamis** [comment]
+1
How about representing all the instances by Region on UI, reading it from state file ? we mostly keep our state files to git so we don't lose the state of it.

**Comment by jippi** [comment]
Closing, i would love to expand hashi-ui on this, but until concrete initial work has done, I don't want it to stay open in the issue tracker - feel free to continue the discussion though :)
