### ISSUE TITLE
Job Resource Stats

### ISSUE THREAD

**Issue by Xopherus** [jippi/hashi-ui#237]
It would be useful to see live resource usage stats on a per-job basis. Right now we have resource stats aggregated at the nomad client level, but that's only useful for monitoring clients. 

One common use case my team is dealing with is ensuring that we correctly allocate resources for each job. By that I mean we provide enough resources for the job to run but not too much to be overprovisioned. By having job resource stats you could validate that you're optimizing resources on a per-job basis.

**Comment by rejeep** [comment]
Would love to see this feature! 👍

**Comment by jippi** [comment]
Me too ! :D

**Comment by jippi** [comment]
Is this per job or per allocation ? :)

**Comment by jcua** [comment]
I believe this is per allocation. I tried to pull this information before but without success. This was my previous attempt.

1. Get the full allocation id by using this (because the API does not work with the shorten form of the allocation id):
   `curl -k https://nomad:4646/v1/allocations | jq '.[] | [.JobID, .ID, .TaskGroup, .ClientStatus ] | join (" ")' | grep running`

2. Use this endpoint https://www.nomadproject.io/docs/http/client-allocation-stats.html
   Note: that this has to be called against each client and not against the nomad server.
   Then using the example above, under the "Tasks", there are 2 Pids, one is for the nomad executor, and the other is for the tasks itself. We want the resources related to the tasks

But imagine if you have 3 client servers, and let say your nomad job has task_count=3, then nomad will use the 3 client servers. This means that you have to do (2) again for all the client servers if you want to aggregate the resources used by this job.

**Comment by jippi** [comment]
this is in master now thanks to @hsmade - will be out in 0.20.0 :)

**Comment by Xopherus** [comment]
Awesome!
