### ISSUE TITLE
Improve Nomad Cluster view

### ISSUE THREAD

**Issue by alxark** [jippi/hashi-ui#299]
Hello. I would like to make a small proposal. Currently you are using round charts to display cluster load. IMHO it's not optimal and as you can see there is a big blank are on the screen. I think it will be better to use some kind of progress bar. This will reduce total consumed area and should be more useful.

![screen shot 2017-08-28 at 12 02 35](https://user-images.githubusercontent.com/20012119/29770851-d79a0f6c-8be8-11e7-954c-0f2a2432e28d.png)

**Comment by lfarnell** [comment]
@alxark I will defer to @jippi on this one but i don't think this is a change that would be made. I personally don't think a progress bar would convey the usage as well as a donut chart.  I can see that maybe the card is a little bigger then it may need to be and a code change could fix that. Another possibility could be using a gauge chart instead of a donut chart? This could take up less real estate as well.

**Comment by alxark** [comment]
@lfarnell gauge chart might be better. I'm not a design master but in my opinion donut charts looks terrible now. I think it should be changed. Gauge chart + legend on the right side might be better and consume less space.

**Comment by jippi** [comment]
I really want to redesign that page :)

**Comment by jippi** [comment]
I think the latest improvements have helped quite a lot :) 

if not, please open new issue with improvements
