### ISSUE TITLE
HashiUI RSS Memory allocation

### ISSUE THREAD

**Issue by Bandic007** [jippi/hashi-ui#421]
Hi,
we are observing strange behavior of HashiUI and wanted to know if this is expected or not.
When we start HashiUI it takes very small amount of resistant memory. But when it gets opened several times, it starts taking more and more memory and sometimes it gets to 3.5/4 GB of memory allocated and triggers our OOM killer.

Using GDB we've dumped a memory address, where the HashiUI is placed and saw that in the memory the UI is keeping all requests, made from the browser when opening it. They are not stored in the cache, but in the resistant memory. Is this normal - to keep all requests in the memory and the UI to eat so much memory? There is no other way to lower its memory consumption, than restarting the HashiUI/

**Comment by jippi** [comment]
it's likely a bug :)

**Comment by Bandic007** [comment]
@jippi - are you going to check and try to fix it in some next build or patch?
Or at lease give some advice how to deal with this util it gets fixed?
Thanks!

**Comment by jippi** [comment]
I don't think I will get time to look into it in 2018 tbh.

My bad recommendation is to accept the occasional OOM.

We run 2 alloc with ~1GB ram each, so when one OOM, a refresh brings you right back to working, while the nomad alloc restarts

**Comment by Bandic007** [comment]
@jippi will you find some time in the next months to try to fix this? It is really bugging our current setup. Please!

**Comment by jippi** [comment]
months, probably yes - probably mid/end feb :)

**Comment by Bandic007** [comment]
@jippi  - can we expect some work on this this month as you told above? :)

**Comment by Bandic007** [comment]
@jippi 
any info will you have time?

**Comment by jippi** [comment]
Probably not until March :)

**Comment by Bandic007** [comment]
@jippi
any info will you have time this month?

**Comment by josegonzalez** [comment]
@Bandic007 As you might be aware, this is an open source project. The author may or may not have time to fix bugs or implement a feature, but is under no requirement to do either - the MIT license says as much. I'd imagine the author is quite busy with work, and as such, paying their own bills takes priority over a bug that doesn't cause them much day-to-day stress.

If you wish to have this issue fixed, rather than asking for periodic updates, I would suggest one of the following two things:

- Offering to pay for the development time it would take to fix this (I would say its around 2 days of work).
- Dedicating development resources (either your own or from the team you are on) to fix the issue.

I hope this doesn't come off as an aggressive response, but I'd like to save you some time in the future in case you are thinking of asking again in a few days as to any updates :)
