### ISSUE TITLE
Error: Unable to connect to the backend...if basic authentication is enabled 

### ISSUE THREAD

**Issue by chudamanisanju** [jippi/hashi-ui#432]
I have enabled basic authentication and getting Error: Unable to connect to the backend...

**Comment by jippi** [comment]
Hi!,

What authentication? hashi-ui don't have any authentication features :)

**Comment by chudamanisanju** [comment]
Thats true, but I applied basic authentication from fabio using auth tag in urlprefix.

_tags  = ["urlprefix-nomad.service.consul/","urlprefix-nomad.domain.com/ proto=http auth=mybasicauth"]_

**Comment by jippi** [comment]
The issue is w/Fabio then, we (@SeatGeek) use basic auth from nginx via a config similar to https://github.com/jippi/hashi-ui/tree/master/scripts/nginx-frontend-proxy and it works fine. 

There are 0 config/handling in hashi-ui for auth, so having the headers won't change the behavior of hashi-ui - so from your debugging next steps, i would only look to the fabio config

Heads up that you use `nomad` as service name in fabio, this is same consul service name as *nomad servers* normally, so might be root cause
